services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: tera-mssql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=pass
    ports:
      - "1433:1433"
    volumes:
      - ./data/mssql:/var/opt/mssql

  postgres:
    image: postgres:latest
    container_name: tera-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data