services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: tera-mssql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong@Passw0rd
    ports:
      - "1433:1433"
    volumes:
      # Mapeia apenas a pasta de arquivos de dados
      - ./data/mssql/data:/var/opt/mssql/data
      # Opcional: log em host
      - ./data/mssql/log:/var/opt/mssql/log